spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book-nexus
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      database: postgresql
  mail:
    host: localhost
    port: 1025
    username: rahil
    password: rahil
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connection-timeout: 5000
        timeout: 3000
        write-timeout: 5000
