services:
  postgres:
    container_name: postgres-sql-book-nexus
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: book-nexus
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - book-nexus-network
    restart: unless-stopped
  mail-dev:
    container_name: mail-dev-book-nexus
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025


networks:
  book-nexus-network:
    driver: bridge

volumes:
  postgres:
    driver: local